name: Publish Docker image

on:
  push:
    branches:
      - 'main'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  push_fpm_to_registry:
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        version:
          - number: 7.4
          - number: "8.0"
          - number: 8.1
          - number: 8.2
          - number: 8.3
          - number: 8.4
        type: [ fpm, debug ]

    runs-on: ubuntu-latest
    name: Build "evoweb/php:${{ matrix.version.number }}-${{ matrix.type }}" and push it to repository

    steps:
      - uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: evoweb/php

      - name: Build Docker image
        id: build
        continue-on-error: true
        uses: docker/build-push-action@v5
        with:
          file: web/${{ matrix.version.number }}/Dockerfile
          context: .
          load: true
          build-args: |
            TYPE=${{ matrix.type }}
            VERSION=${{ matrix.version.number }}
          tags: evoweb/php:${{ matrix.version.number }}-${{ matrix.type }}

      - name: Test the build image
        if: steps.build.outputs.imageid != ''
        run: |
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/php:${{ matrix.version.number }}-${{ matrix.type }} php -v

      - name: Log in to Docker Hub
        if: steps.build.outputs.imageid != '' && github.event_name != 'pull_request' && github.ref_name != 'main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        if: steps.build.outputs.imageid != '' && github.event_name != 'pull_request' && github.ref_name != 'main'
        uses: docker/build-push-action@v5
        with:
          file: web/${{ matrix.version.number }}/Dockerfile
          context: .
          build-args: |
            TYPE=${{ matrix.type }}
            VERSION=${{ matrix.version.number }}
            ADDITIONAL_PACKAGES=${{ matrix.version.packages }}
          push: ${{ github.event_name != 'pull_request' && github.ref_name != 'main' }}
          tags: |
            evoweb/php:${{ matrix.version.number }}-${{ matrix.type }}
            evoweb/php:${{ matrix.version.number }}-${{ matrix.type }}-${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}

  push_others_to_registry:
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        type: [ crontab, composer, composer-node ]

    runs-on: ubuntu-latest
    name: Build "evoweb/php:${{ matrix.type }}" and push it to repository

    steps:
      - uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: evoweb/php

      - name: Build Docker image
        id: build
        continue-on-error: true
        uses: docker/build-push-action@v5
        with:
          file: ${{ matrix.type }}/Dockerfile
          context: .
          load: true
          tags: evoweb/php:${{ matrix.type }}

      - name: Test the build image
        if: steps.build.outputs.imageid != ''
        run: |
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/php:${{ matrix.type }} php -v

      - name: Log in to Docker Hub
        if: steps.build.outputs.imageid != '' && github.event_name != 'pull_request' && github.ref_name != 'main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        if: steps.build.outputs.imageid != '' && github.event_name != 'pull_request' && github.ref_name != 'main'
        uses: docker/build-push-action@v5
        with:
          file: ${{ matrix.type }}/Dockerfile
          context: .
          push: ${{ github.event_name != 'pull_request' && github.ref_name != 'main' }}
          tags: |
            evoweb/php:${{ matrix.type }}
            evoweb/php:${{ matrix.type }}-latest
            evoweb/php:${{ matrix.type }}-${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
