name: Publish Docker image

on:
  push:
    branches:
      - 'main'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        version: [7.4, 8.0, 8.1, 8.2, 8.3]
        variants: [crontab, debug, fpm]

    name: Build "evoweb/php:${{ matrix.version }}-${{ matrix.variants }}" and push it to repository

    steps:
      - uses: actions/checkout@v3

      - name: Check if variant exists
        id: file-exists
        run: if [ -f "${{ matrix.version }}/${{ matrix.variants }}/Dockerfile" ]; then fe=1; else fe=0; fi

      - run: echo "fe is $fe"

      - name: Extract metadata (tags, labels) for Docker
        if: steps.file-exists.outputs.fe == 1
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: evoweb/php

      - name: Log in to Docker Hub
        if: steps.file-exists.outputs.fe == 1 && github.event_name != 'pull_request' && github.ref_name != 'main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: steps.file-exists.outputs.fe == 1
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.version }}/${{ matrix.variants }}
          push: ${{ github.event_name != 'pull_request' && github.ref_name != 'main' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/php:${{ matrix.version }}-${{ matrix.variants }}-${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
