name: Publish Docker image

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  push_to_registry:
    strategy:
      fail-fast: false
      matrix:
        meta:
          - name: PHP 7.4 fpm
            directory: 7.4
            tags: |
              evowebde/php:latest
              evowebde/php:7.4
          - name: PHP 8.0 crontab
            directory: 8.0-crontab
            tags: |
              evowebde/php:8.0-crontab
          - name: PHP 8.2
            directory: 8.2
            tags: |
              evowebde/php:8.2

    name: Build "${{ matrix.meta.name }}" and push it to repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: evowebde/php

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.meta.directory }}
          push: true
          tags: ${{ matrix.meta.tags }}
          labels: ${{ steps.meta.outputs.labels }}
