name: Publish Docker image

on:
  push:
    branches:
      - 'main'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        directory:
          - 7.4
          - 7.4-debug
          - 8.1
          - 8.1-debug
          - 8.2
          - 8.2-debug
          - 8.0-crontab

    name: Build "evoweb/php:${{ matrix.directory }}" and push it to repository

    steps:
      - uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: evoweb/php

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.directory }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/php:${{ matrix.directory }}-${{ github.ref }}
          labels: ${{ steps.meta.outputs.labels }}
