name: Publish Docker image

on:
  push:
    branches:
      - 'main'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  push_fpm_to_registry:
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        version:
          - number: 7.4
            packages: php7.4-json
          - number: 8.0
          - number: 8.1
          - number: 8.2
          - number: 8.3
        variant: [ fpm, debug ]

    runs-on: ubuntu-latest
    name: Build "evoweb/php:${{ matrix.version.number }}-${{ matrix.variant }}" and push it to repository

    steps:
      - uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: evoweb/php

      - name: Build Docker image
        id: build
        continue-on-error: true
        uses: docker/build-push-action@v5
        with:
          file: web/Dockerfile
          context: .
          load: true
          build-args: |
            TYPE=${{ matrix.variant }}
            VERSION=${{ matrix.version.number }}
            ADDITIONAL_PACKAGES=${{ matrix.version.packages }}
          tags: evoweb/php:${{ matrix.version.number }}-${{ matrix.variant }}

      - name: Test the build image
        if: steps.build.outputs.imageid != ''
        run: |
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/php:${{ matrix.version.number }}-${{ matrix.variant }} php -v

      - name: Log in to Docker Hub
        if: steps.build.outputs.imageid != '' && github.event_name != 'pull_request' && github.ref_name != 'main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        if: steps.build.outputs.imageid != '' && github.event_name != 'pull_request' && github.ref_name != 'main'
        uses: docker/build-push-action@v5
        with:
          file: web/Dockerfile
          context: .
          build-args: |
            TYPE=${{ matrix.variant }}
            VERSION=${{ matrix.version.number }}
            ADDITIONAL_PACKAGES=${{ matrix.version.packages }}
          push: ${{ github.event_name != 'pull_request' && github.ref_name != 'main' }}
          tags: |
            evoweb/php:${{ matrix.version.number }}-${{ matrix.variant }}
            evoweb/php:${{ matrix.version.number }}-${{ matrix.variant }}-${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}

  push_others_to_registry:
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        variant: [ crontab, composer ]

    runs-on: ubuntu-latest
    name: Build "evoweb/php:${{ matrix.variant }}" and push it to repository

    steps:
      - uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: evoweb/php

      - name: Build Docker image
        id: build
        continue-on-error: true
        uses: docker/build-push-action@v5
        with:
          file: ${{ matrix.variant }}/Dockerfile
          context: .
          load: true
          tags: evoweb/php:${{ matrix.variant }}

      - name: Test the build image
        if: steps.build.outputs.imageid != ''
        run: |
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/php:${{ matrix.variant }} php -v

      - name: Log in to Docker Hub
        if: steps.build.outputs.imageid != '' && github.event_name != 'pull_request' && github.ref_name != 'main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        if: steps.build.outputs.imageid != '' && github.event_name != 'pull_request' && github.ref_name != 'main'
        uses: docker/build-push-action@v5
        with:
          file: ${{ matrix.variant }}/Dockerfile
          context: .
          push: ${{ github.event_name != 'pull_request' && github.ref_name != 'main' }}
          tags: |
            evoweb/php:${{ matrix.variant }}
            evoweb/php:${{ matrix.variant }}-${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
